language: python
python: 2.7
env:
  - TOX_ENV=py27
  - TOX_ENV=flake8
install:
  - pip install tox
script:
  - tox -e $TOX_ENV
notifications:
  webhooks:
    urls:
      - http://n.tkte.ch/h/2689/bYIuyJQRwH5nfdGQu-jbjv23